// src/components/userData.js
const userData = [
  {
    login: { uuid: '1' },
    name: { title: 'Mr', first: 'Eemil', last: 'Couri' },
    location: { city: 'Posio', country: 'Finland' },
    email: 'eemil.couri@example.com',
    phone: '03-543-310',
    picture: { large: 'https://randomuser.me/api/portraits/men/35.jpg' },
  },
  {
    login: { uuid: '2' },
    name: { title: 'Miss', first: 'Carola', last: 'Wilmsen' },
    location: { city: "'t Haagje", country: 'Netherlands' },
    email: 'carola.wilmsen@example.com',
    phone: '(0087) 647962',
    picture: { large: 'https://randomuser.me/api/portraits/women/42.jpg' },
  },
  {
    login: { uuid: '3' },
    name: { title: 'Mr', first: 'Barry', last: 'Murray' },
    location: { city: 'Portlaoise', country: 'Ireland' },
    email: 'barry.murray@example.com',
    phone: '021-079-8712',
    picture: { large: 'https://randomuser.me/api/portraits/men/32.jpg' },
  },
  {
    login: { uuid: '4' },
    name: { title: 'Mrs', first: 'Naomi', last: 'Allen' },
    location: { city: 'Manchester', country: 'United Kingdom' },
    email: 'naomi.allen@example.com',
    phone: '0161-555-0171',
    picture: { large: 'https://randomuser.me/api/portraits/women/44.jpg' },
  },
  {
    login: { uuid: '5' },
    name: { title: 'Mr', first: 'James', last: 'Smith' },
    location: { city: 'Sydney', country: 'Australia' },
    email: 'james.smith@example.com',
    phone: '02-555-0171',
    picture: { large: 'https://randomuser.me/api/portraits/men/45.jpg' },
  },
  {
    login: { uuid: '6' },
    name: { title: 'Miss', first: 'Linda', last: 'Taylor' },
    location: { city: 'Vancouver', country: 'Canada' },
    email: 'linda.taylor@example.com',
    phone: '604-555-0171',
    picture: { large: 'https://randomuser.me/api/portraits/women/34.jpg' },
  },
  {
    login: { uuid: '7' },
    name: { title: 'Mr', first: 'Carlos', last: 'Santos' },
    location: { city: 'São Paulo', country: 'Brazil' },
    email: 'carlos.santos@example.com',
    phone: '+55 11 5555-0171',
    picture: { large: 'https://randomuser.me/api/portraits/men/41.jpg' },
  },
  {
    login: { uuid: '8' },
    name: { title: 'Mrs', first: 'Sofia', last: 'Garcia' },
    location: { city: 'Madrid', country: 'Spain' },
    email: 'sofia.garcia@example.com',
    phone: '+34 91 555 0171',
    picture: { large: 'https://randomuser.me/api/portraits/women/47.jpg' },
  },
  {
    login: { uuid: '9' },
    name: { title: 'Mr', first: 'Liam', last: "O'Connor" },
    location: { city: 'Cork', country: 'Ireland' },
    email: 'liam.oconnor@example.com',
    phone: '+353 21 555 0171',
    picture: { large: 'https://randomuser.me/api/portraits/men/55.jpg' },
  },
  {
    login: { uuid: '10' },
    name: { title: 'Ms', first: 'Marie', last: 'Dupont' },
    location: { city: 'Paris', country: 'France' },
    email: 'marie.dupont@example.com',
    phone: '+33 1 555 0171',
    picture: { large: 'https://randomuser.me/api/portraits/women/52.jpg' },
  },
];

export default userData;
